const qbPhotos: { [key: string]: string } = {
  'Patrick Mahomes': '/qbs/mahomes.jpg',
  'Tom Brady': '/qbs/brady.jpg',
  'Peyton Manning': '/qbs/manning.jpg',
  'Brett Favre': '/qbs/favre.jpg',
  'Drew Brees': '/qbs/brees.jpg',
  'Ben Roethlisberger': '/qbs/roethlisberger.jpg',
  'Philip Rivers': '/qbs/rivers.jpg',
  'Eli Manning': '/qbs/eli.jpg',
  'Aaron Rodgers': '/qbs/rodgers.jpg',
  'Matt Ryan': '/qbs/ryan.jpg',
  'Russell Wilson': '/qbs/wilson.jpg',
  'Matthew Stafford': '/qbs/stafford.jpg',
  'Kirk Cousins': '/qbs/cousins.jpg',
  'Derek Carr': '/qbs/carr.jpg',
  'Ryan Tannehill': '/qbs/tannehill.jpg',
  'Jared Goff': '/qbs/goff.jpg',
  'Carson Wentz': '/qbs/wentz.jpg',
  'Baker Mayfield': '/qbs/mayfield.jpg',
  'Sam Darnold': '/qbs/darnold.jpg',
  'Josh Allen': '/qbs/allen.jpg',
  'Lamar Jackson': '/qbs/jackson.jpg',
  'Kyler Murray': '/qbs/murray.jpg',
  'Daniel Jones': '/qbs/jones.jpg',
  'Dwayne Haskins': '/qbs/haskins.jpg',
  'Drew Lock': '/qbs/lock.jpg',
  'Gardner Minshew': '/qbs/minshew.jpg',
  'Tua Tagovailoa': '/qbs/tua.jpg',
  'Justin Herbert': '/qbs/herbert.jpg',
  'Joe Burrow': '/qbs/burrow.jpg',
  'Jalen Hurts': '/qbs/hurts.jpg',
  'Trevor Lawrence': '/qbs/lawrence.jpg',
  'Zach Wilson': '/qbs/wilson.jpg',
  'Mac Jones': '/qbs/mac.jpg',
  'Davis Mills': '/qbs/mills.jpg',
  'Justin Fields': '/qbs/fields.jpg',
  'Trey Lance': '/qbs/lance.jpg',
  'Kenny Pickett': '/qbs/pickett.jpg',
  'Brock Purdy': '/qbs/purdy.jpg',
  'Desmond Ridder': '/qbs/ridder.jpg',
  'Sam Howell': '/qbs/howell.jpg',
  'C.J. Stroud': '/qbs/stroud.jpg',
  'Bryce Young': '/qbs/young.jpg',
  'Anthony Richardson': '/qbs/richardson.jpg',
  'Will Levis': '/qbs/levis.jpg'
};

export function getQBPhoto(qb: string): string {
  return qbPhotos[qb] || '';
} 