export const teamColors: Record<string, string> = {
  "Arizona Cardinals": "text-red-500",
  "Atlanta Falcons": "text-red-500",
  "Baltimore Ravens": "text-purple-500",
  "Buffalo Bills": "text-blue-500",
  "Carolina Panthers": "text-blue-500",
  "Chicago Bears": "text-blue-500",
  "Cincinnati Bengals": "text-orange-500",
  "Cleveland Browns": "text-orange-500",
  "Dallas Cowboys": "text-blue-500",
  "Denver Broncos": "text-orange-500",
  "Detroit Lions": "text-blue-500",
  "Green Bay Packers": "text-green-500",
  "Houston Texans": "text-blue-500",
  "Indianapolis Colts": "text-blue-500",
  "Jacksonville Jaguars": "text-teal-500",
  "Kansas City Chiefs": "text-red-500",
  "Las Vegas Raiders": "text-gray-500",
  "Los Angeles Chargers": "text-blue-500",
  "Los Angeles Rams": "text-blue-500",
  "Miami Dolphins": "text-teal-500",
  "Minnesota Vikings": "text-purple-500",
  "New England Patriots": "text-blue-500",
  "New Orleans Saints": "text-gold-500",
  "New York Giants": "text-blue-500",
  "New York Jets": "text-green-500",
  "Philadelphia Eagles": "text-green-500",
  "Pittsburgh Steelers": "text-yellow-500",
  "San Francisco 49ers": "text-red-500",
  "Seattle Seahawks": "text-blue-500",
  "Tampa Bay Buccaneers": "text-red-500",
  "Tennessee Titans": "text-blue-500",
  "Washington Commanders": "text-red-500"
}; 